-- =============================================================================
-- Seed: Top 50 Nigerian Tech Companies
-- Run in Supabase SQL Editor after schema.sql
-- =============================================================================

INSERT INTO companies (name, industry, stage, headquartered_in_nigeria) VALUES
  ('Paystack', 'Fintech', 'Growth stage (Series C+)', TRUE),
  ('Flutterwave', 'Fintech', 'Growth stage (Series C+)', TRUE),
  ('Moniepoint', 'Fintech', 'Growth stage (Series C+)', TRUE),
  ('Kuda Bank', 'Fintech', 'Growth stage (Series C+)', TRUE),
  ('OPay', 'Fintech', 'Growth stage (Series C+)', TRUE),
  ('PalmPay', 'Fintech', 'Growth stage (Series C+)', TRUE),
  ('Carbon', 'Fintech', 'Growth stage (Series C+)', TRUE),
  ('FairMoney', 'Fintech', 'Growth stage (Series C+)', TRUE),
  ('Piggyvest', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('Cowrywise', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('Interswitch', 'Fintech', 'Established (non-startup)', TRUE),
  ('Andela', 'SaaS', 'Growth stage (Series C+)', TRUE),
  ('Jumia', 'E-commerce', 'Public / Listed', TRUE),
  ('Konga', 'E-commerce', 'Established (non-startup)', TRUE),
  ('Zedvance Finance Limited', 'Financial Services', 'Established (non-startup)', TRUE),
  ('54gene', 'Healthtech', 'Growth stage (Series C+)', TRUE),
  ('mDoc', 'Healthtech', 'Early stage (Series A-B)', TRUE),
  ('Helium Health', 'Healthtech', 'Early stage (Series A-B)', TRUE),
  ('Bamboo', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('Risevest', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('Chipper Cash', 'Fintech', 'Growth stage (Series C+)', TRUE),
  ('Brass', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('Mono', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('Stears', 'SaaS', 'Early stage (Series A-B)', TRUE),
  ('Termii', 'SaaS', 'Early stage (Series A-B)', TRUE),
  ('Thepeer', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('Buycoins', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('Bundle Africa', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('SeamlessHR', 'HRTech', 'Early stage (Series A-B)', TRUE),
  ('BuyPower', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('MAX', 'Logistics', 'Growth stage (Series C+)', TRUE),
  ('Kobo360', 'Logistics', 'Early stage (Series A-B)', TRUE),
  ('Gokada', 'Logistics', 'Early stage (Series A-B)', TRUE),
  ('Reliance HMO', 'Healthtech', 'Early stage (Series A-B)', TRUE),
  ('Paga', 'Fintech', 'Established (non-startup)', TRUE),
  ('SystemSpecs', 'Fintech', 'Established (non-startup)', TRUE),
  ('Nomba', 'Fintech', 'Growth stage (Series C+)', TRUE),
  ('Prospa', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('Grey', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('Indicina', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('Lendsqr', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('TalentQL (AltSchool Africa)', 'Edtech', 'Early stage (Series A-B)', TRUE),
  ('Decagon', 'Edtech', 'Early stage (Series A-B)', TRUE),
  ('uLesson', 'Edtech', 'Early stage (Series A-B)', TRUE),
  ('Lidya', 'Fintech', 'Early stage (Series A-B)', TRUE),
  ('Sabi', 'E-commerce', 'Early stage (Series A-B)', TRUE),
  ('TradeDepot', 'E-commerce', 'Early stage (Series A-B)', TRUE),
  ('Omnibiz', 'E-commerce', 'Early stage (Series A-B)', TRUE),
  ('Shuttlers', 'Logistics', 'Early stage (Series A-B)', TRUE),
  ('Patricia', 'Fintech', 'Early stage (Series A-B)', TRUE)
ON CONFLICT (name) DO NOTHING;
